
title: AnhNg's journal
baseurl: "/journal" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  Ducanhnguyen1022


exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/
  - README.md
  - LICENSE
  - package.json
  - package-lock.json
  - yarn.lock
  - .gitignore
  - .github/

show_excerpts: false

# Build settings

plugins:
  - jekyll-paginate

# Pagination
paginate: 25
paginate_path: "/page:num/"

# Vô hiệu hóa highlighter
highlighter: none

kramdown:
  syntax_highlighter: null
  input: GFM
  hard_wrap: false

sass:
  style: compressed


compress_html:
  clippings: all
  comments: all
  blanklines: false

